#!/bin/bash
# Perform the backup

echo
echo Backup triggered

if [ -z "${TMPDIR}" ]; then 
    TMPDIR='/tmp/'
fi

source /root/.envs
if test "$(ls -A "/upload")"; then
    tar -zcf $TMPDIR/$(date '+%Y-%m-%dT%H:%M:%S').tar.gz /upload
    aws s3 cp $TMPDIR/*.tar.gz s3://$AWS_BUCKET/
    rm $TMPDIR/*.tar.gz
else
    echo The upload directory is empty, nothing to do
fi
